# Generated by Django 2.1.3 on 2018-11-17 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181117_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
                ('sigla_uf', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilNinja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=500)),
                ('dt_nasc', models.DateField()),
                ('twitter', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=500)),
                ('instagram', models.CharField(max_length=500)),
                ('telegram', models.CharField(max_length=500)),
                ('profissao', models.CharField(max_length=500)),
                ('bio', models.TextField(max_length=500, verbose_name='bio')),
                ('gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Prefiro não declarar')], null=True)),
                ('orient_sex', models.IntegerField(choices=[(0, 'Heterossexual'), (1, 'Homossexual'), (2, 'Bissexual'), (3, 'Pansexual'), (4, 'Assexual'), (5, 'Fluido'), (6, 'Prefiro não declarar')], null=True)),
                ('ident_genero', models.IntegerField(choices=[(0, 'Cisgênero'), (1, 'Transgênero'), (2, 'Neutro ou Não-binario'), (3, 'Prefiro não declarar')], null=True)),
                ('etnia', models.IntegerField(choices=[(0, 'Negra'), (1, 'Indígena'), (2, 'Asiática'), (3, 'Caucasiana'), (4, 'Mestiça'), (5, 'Outra')], null=True)),
                ('causas', models.ManyToManyField(to='account.Causa')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Cidade')),
                ('habilidades', models.ManyToManyField(to='account.Habilidade')),
                ('interesses', models.ManyToManyField(to='account.Interesse')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='etnia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ident_genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orient_sex',
        ),
        migrations.AddField(
            model_name='perfilninja',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Pais'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Estado'),
        ),
    ]
