# Generated by Django 2.1.3 on 2018-11-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181117_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('pais', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=15)),
                ('dataNascimento', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('etnia', models.CharField(max_length=10)),
                ('orientacao', models.CharField(max_length=10)),
                ('identidade', models.CharField(max_length=10)),
                ('twitter', models.CharField(max_length=10)),
                ('facebook', models.CharField(max_length=10)),
                ('instagram', models.CharField(max_length=10)),
                ('telegram', models.CharField(max_length=10)),
                ('causas', models.CharField(max_length=10)),
                ('bio', models.CharField(max_length=10)),
                ('profissao', models.CharField(max_length=10)),
            ],
        ),
    ]
