# Generated by Django 2.1.3 on 2018-11-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_ninja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ninja',
        ),
        migrations.RenameField(
            model_name='perfilninja',
            old_name='dt_nasc',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='perfilninja',
            old_name='gender',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='perfilninja',
            old_name='ident_genero',
            new_name='identidade_genero',
        ),
        migrations.RenameField(
            model_name='perfilninja',
            old_name='orient_sex',
            new_name='orientacao_sexual',
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Pais'),
        ),
    ]
